name: DiffAD
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10.15
  - pip=24.2
  - cudatoolkit=11.8
  - pytorch=2.1.0
  - torchvision=0.16.0
  - numpy=1.23.1
  - pip:
    - albumentations==1.3.0
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.5.0
    - omegaconf==2.3.0
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.37.0
    - imgaug
